config/routes.rb
NbaProject::Application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

    resources :players, only: [:index, :show] do
      collection do 
        get 'search/:q', :action => 'search', :as => 'search'
      end
    end
   
    resources :user_players, only: [:index, :new, :create, :destroy]
    resources :users, only: [:index, :show]
    resources :user_lineups, only: [:index, :show]
    
    resources :teams, only: [:index, :show]

    root 'landings#index'

    #->Prelang (user_login:devise/stylized_paths)
    devise_scope :user do
      get    "login"   => "devise/sessions#new",         as: :new_user_session
      post   "login"   => "devise/sessions#create",      as: :user_session
      delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
      
      get    "signup"  => "devise/registrations#new",    as: :new_user_registration
      post   "signup"  => "devise/registrations#create", as: :user_registration
      put    "signup"  => "devise/registrations#update", as: :update_user_registration
      delete "signup"  => "users/registrations#destroy", as: :destroy_user
      get    "account" => "devise/registrations#edit",   as: :edit_user_registration
    end

    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/letter_opener"
    end
  end
end

app/views/elements/_cookies.html.slim
-if first_time_visit?  
  .cookies.alert-dismissible role="alert"
    p
      .btn.btn-warning.pull-right data-dismiss="alert" 
        = it('common.accept')
      | 
        = it('common.cookies') 

app/views/elements/_footer.html.slim
footer
  .container
    .row
      .col-md-3
        = select_tag 'language_select',
                     language_options,
                     onchange: "window.open(this.options[this.selectedIndex].value,'_top')",
                     class: 'form-control'
    .row
      p.text-center
        | Copyright ©
        = it('landing.main_title')
        '
        = Date.current.year

app/views/elements/_navbar.html.slim
nav.navbar.navbar-default role="navigation" 
  /! Brand and toggle get grouped for better mobile display
  .navbar-header
    button.navbar-toggle data-target="#navbar-collapse-1" data-toggle="collapse" type="button" 
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    = link_to image_tag('encestado.png', height: '100%'), defined?(root_path) ? root_path : "#", class: "navbar-brand"
  
  /! Collect the nav links, forms, and other content for toggling
  #navbar-collapse-1.collapse.navbar-collapse
    ul.nav.navbar-nav
    ul.nav.navbar-nav.navbar-right
      li= link_to users_path do
        => glyph :stats
        = it 'navbar.ranking'
      li= link_to it('navbar.teams'), teams_path
      li= link_to it('navbar.players'), players_path
      li= link_to it('navbar.my_team'), user_players_path if user_signed_in?
      - if defined?(Devise)
        - if user_signed_in?
          li= link_to it('navbar.roster'), user_lineups_path
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#" 
              = it('navbar.account')
              b.caret
            ul.dropdown-menu
              li= link_to it('navbar.edit_ac'), edit_user_registration_path
              li.divider
              li= link_to it('navbar.signout'), destroy_user_session_path, method: :delete
        - else
          li= link_to it('navbar.login'), new_user_session_path
          li= link_to it('navbar.signup'), new_user_registration_path
      li
        #search.search-open style="display:none;"
          form.navbar-form role="search" 
            .input-group
              input#srch-term.form-control.typeahead name="srch-term" placeholder=(it('navbar.search')) type="text" 
      li.hidden-sm.hidden-xs
        a.search
          span.glyphicon.glyphicon-search.search-btn