config/routes.rb
NbaProject::Application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

    resources :players, only: [:index, :show] do
      collection do 
        get 'search/:q', :action => 'search', :as => 'search'
      end
    end
   
    resources :user_players, only: [:index, :new, :create, :destroy]
    resources :users, only: [:index, :show]
    resources :user_lineups, only: [:index, :show]
    
    resources :teams, only: [:index, :show]

    root 'landings#index'

    #->Prelang (user_login:devise/stylized_paths)
    devise_scope :user do
      get    "login"   => "devise/sessions#new",         as: :new_user_session
      post   "login"   => "devise/sessions#create",      as: :user_session
      delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
      
      get    "signup"  => "devise/registrations#new",    as: :new_user_registration
      post   "signup"  => "devise/registrations#create", as: :user_registration
      put    "signup"  => "devise/registrations#update", as: :update_user_registration
      delete "signup"  => "users/registrations#destroy", as: :destroy_user
      get    "account" => "devise/registrations#edit",   as: :edit_user_registration
    end

    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/letter_opener"
    end
  end
end

app/models/user_lineup.rb
class UserLineup < ActiveRecord::Base
	belongs_to :user
  belongs_to :player
  belongs_to :week
  
end

app/controllers/user_lineups_controller.rb
class UserLineupsController < ApplicationController
  before_action :require_user_signed_in

  # GET /user_lineups
  # GET /user_lineups.json
  def index
    #@user_lineups = UserLineup.all
    # @weeks = current_user.user_lineups.week.uniq!
    @weeks = Week.all
  end

  # GET /user_lineups/1
  # GET /user_lineups/1.json
  def show
    @user_players = current_user.user_lineups.where(week_id: params[:id])
    @week = Week.find(params[:id])
  end

end

app/views/user_lineups/index.html.slim
h1= t(:user_lineup) 

.row
  - unless @weeks.nil?
    - @weeks.each do |da_week|
      .col-md-3
        .thumbnail
          .caption
            h2.text-center
              = number_with_precision(current_user.points_in_week(da_week), precision: 2)
              |  pts
            h4
              = it('ranking.week_with_id', id: da_week.id)
              | : 
              small= da_week.start_date.strftime("#{da_week.start_date.day.ordinalize} %B, %Y")
            = link_to it('shared.see'), user_lineup_path(da_week), class: 'btn btn-primary', style: 'width: 100%'

app/views/user_lineups/show.html.slim
p#notice = notice


h1 
  = it('user.current_team')
  =@week.id 
h4 style="color: gray"
  = it('shared.from_date')
  = @week.start_date
  = it('shared.to_date')
  = @week.end_date

.row 
  - @user_players.each do |user_player|
    .col-sm-6.col-md-3
      .thumbnail
        = render 'shared/player_image', player: user_player.player
        .caption
          h3= user_player.player.name
          h4
            = number_with_precision(user_player.player.points_in_week(@week), precision: 2)
            |  pts
          p
            = link_to '+Info', player_path(user_player.player), class: 'btn btn-info'