config/routes.rb
NbaProject::Application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

    resources :players, only: [:index, :show] do
      collection do 
        get 'search/:q', :action => 'search', :as => 'search'
      end
    end
   
    resources :user_players, only: [:index, :new, :create, :destroy]
    resources :users, only: [:index, :show]
    resources :user_lineups, only: [:index, :show]
    
    resources :teams, only: [:index, :show]

    root 'landings#index'

    #->Prelang (user_login:devise/stylized_paths)
    devise_scope :user do
      get    "login"   => "devise/sessions#new",         as: :new_user_session
      post   "login"   => "devise/sessions#create",      as: :user_session
      delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
      
      get    "signup"  => "devise/registrations#new",    as: :new_user_registration
      post   "signup"  => "devise/registrations#create", as: :user_registration
      put    "signup"  => "devise/registrations#update", as: :update_user_registration
      delete "signup"  => "users/registrations#destroy", as: :destroy_user
      get    "account" => "devise/registrations#edit",   as: :edit_user_registration
    end

    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/letter_opener"
    end
  end
end

app/models/user_player.rb
class UserPlayer < ActiveRecord::Base
  MAX_NUM_PLAYERS = 8
  BUDGET = 65000000

  belongs_to :user
  belongs_to :player
  validates_with MaxNumTeamPlayersValidator
  validates_with MaxBudgetReachedValidator
  
  # Para evitar tener dos veces el mismo jugador
  validates_uniqueness_of :player_id, scope: :user_id
  
  scope :salary_desc, -> { includes(:player).order('players.salary DESC') }

end

app/controllers/user_players_controller.rb
class UserPlayersController < ApplicationController
  before_action :set_user_player, only: :destroy
  before_action :set_players_available, only: :new
  before_action :require_user_signed_in

  # GET /user_players
  # GET /user_players.json
  def index
    @user_players = current_user.user_players.salary_desc
  end

  # GET /user_players/new
  def new
    @user_player = UserPlayer.new
  end

  # POST /user_players
  # POST /user_players.json
  def create
    @user_player = UserPlayer.new(user_player_params)
    @user_player.user = current_user

    respond_to do |format|
      if @user_player.save
        format.html { redirect_to user_players_path, notice: It.it("players.added", user: @user_player.player.name) }
        format.json { render action: 'show', status: :created, location: @user_player }
      else
        format.html do  
          set_players_available
          render action: 'new' 
        end
        
        format.json { render json: @user_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_players/1
  # DELETE /user_players/1.json
  def destroy
    @user_player.destroy
    respond_to do |format|
      format.html { redirect_to user_players_url, notice: 'Jugador traspasado.' }
      format.json { head :no_content }
      format.js { render nothing: true }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_player
      @user_player = UserPlayer.find(params[:id])
    end
  
  def set_players_available
    @players_available = Player.with_salary.includes(:team) - current_user.players
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_player_params
      params.require(:user_player).permit(:player_id)
    end
end

app/helpers/user_players_helper.rb
module UserPlayersHelper
end

app/views/user_players/_form.html.slim
.col-lg-12
  table.dataTable.table
    thead
      tr
        th.col-lg-4 
          = it 'players.player'
        th.col-lg-4 
          = it 'user.team'
        th.col-lg-4 
          = it 'players.price'
    tbody
      - @players_available.each do |player|
        tr 
          td= link_to player.display_first_last, player
          td= player.team.full_team_name
          td
            = form_for(@user_player, html: { class: 'form-horizontal' }) do |f|
              = number_to_currency(player.salary, precision: 0)
              = f.hidden_field 'player_id', value: player.id 
              .pull-right
                = f.submit it('user.buy_player'), class: 'btn btn-primary'

app/views/user_players/index.html.slim
.row
  .col-lg-12
    .bs-callout.bs-callout-info
      h4
        = it("user.flash_title", week: Week.last_week_id)
      p 
        = it("user.flash_message", b: It.tag(:b))

.row
  .col-xs-12.col-sm-6
    h1
      = it 'user.team'
      |  
      small
        = @user_players.count
        = '/8'
        = ' '
        = number_to_currency(current_user.budget_spent, precision: 0)
        = '/'
        = number_to_currency(UserPlayer::BUDGET, precision: 0)
  -unless current_user.team_complete?
    .col-xs-12.col-sm-6
      = link_to t('user.buy_player'), new_user_player_path, class: 'btn btn-primary btn-lg margin-top-5-xs margin-bottom-5-xs center-block-xs pull-lg-right pull-sm-right pull-md-right'

.row 
  - @user_players.each do |user_player|
    .col-sm-6.col-md-3
      .thumbnail
        = render 'shared/player_image', player: user_player.player
        .caption
          h3= user_player.player.name
          p 
            = number_to_currency(user_player.player.salary, precision: 0)
          p 
            - user_player.player.last_five_games.each do |points|
              span.badge
                = points
          p
            = link_to '+Info', player_path(user_player.player), class: 'btn btn-info'
            = ' '
            = link_to t('players.sell'), 
            user_player_path(user_player.id),
            class: 'delete-player btn btn-danger', 
            method: :delete, 
            data: { confirm: It.it('shared.u_sure') }

app/views/user_players/new.html.slim
= render 'shared/error_messages', object: @user_player
h1
  = it 'user.buy_player'
  br
  small
    = it 'user.budget_left'
    = number_to_currency(current_user.budget_left, precison: 0)
= render 'form'